from app.services.people.base import (
    NormalizedPerson,
    SearchCriteria,
)
from app.services.people.mapper import to_normalized_person


class MockPeopleProvider:
    """
    Local-only people provider.

    Results are synthetic and MUST be labeled as mock in the API
    (`provider: "mock"`) and UI. This is not production search data.
    """

    name = "mock"

    _FIRST_NAMES = (
        "Aisha",
        "Rohan",
        "Meera",
        "Arjun",
        "Priya",
        "Kabir",
        "Ananya",
        "Dev",
        "Sana",
        "Nikhil",
    )

    _LAST_NAMES = (
        "Sample",
        "Mockwell",
        "Demo",
        "Fixture",
        "Placeholder",
        "Example",
        "Sandbox",
        "Trial",
        "Preview",
        "Stub",
    )

    def search_people(
        self,
        criteria: SearchCriteria,
        limit: int = 10,
    ) -> list[NormalizedPerson]:
        count = min(max(limit, 0), 10)
        people: list[NormalizedPerson] = []

        for index in range(count):
            people.append(self._build_person(criteria, index))

        return people

    def get_person(self, person_id: str) -> NormalizedPerson | None:
        if not person_id.startswith("mock:"):
            return None

        provider_id = person_id.split(":", 1)[1]

        if not provider_id.startswith("local-"):
            return None

        try:
            index = int(provider_id.replace("local-", "", 1))
        except ValueError:
            return None

        return self._build_person(SearchCriteria(), index)

    def _build_person(
        self,
        criteria: SearchCriteria,
        index: int,
    ) -> NormalizedPerson:
        first_name = self._FIRST_NAMES[index % len(self._FIRST_NAMES)]
        last_name = self._LAST_NAMES[index % len(self._LAST_NAMES)]
        title = criteria.job_title or "Software Engineer"
        location = criteria.location or "Remote"
        skills = criteria.skills[:5] if criteria.skills else ["Python"]
        company = criteria.company or f"Mock Co {index + 1}"

        return to_normalized_person(
            provider=self.name,
            provider_id=f"local-{index}",
            raw={
                "first_name": first_name,
                "last_name": last_name,
                "full_name": f"{first_name} {last_name}",
                "job_title": title,
                "company_name": company,
                "company_website": None,
                "location": location,
                "linkedin_url": None,
                "skills": skills,
                "headline": (
                    f"Mock profile for {title} search "
                    f"(not real candidate data)"
                ),
                "summary": (
                    "This profile was generated by the local mock people "
                    "provider so the recruiter UI can be tested. It is not "
                    "a real person from PDL, Apollo, or Coresignal."
                ),
                "email": None,
                "phone": None,
                "experience": [
                    {
                        "title": title,
                        "company": company,
                        "start_date": "2022",
                        "end_date": "Present",
                        "description": "Synthetic experience for UI testing.",
                    }
                ],
                "education": [
                    {
                        "school": "Mock University",
                        "degree": "B.Tech",
                        "field": "Computer Science",
                        "start_date": "2014",
                        "end_date": "2018",
                    }
                ],
            },
        )
